/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.smalluml.parser.antlr.internal.InternalSmallUmlParser;
import org.smalluml.services.SmallUmlGrammarAccess;

public class SmallUmlParser extends AbstractAntlrParser {

	@Inject
	private SmallUmlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmallUmlParser createParser(XtextTokenStream stream) {
		return new InternalSmallUmlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Attribute";
	}

	public SmallUmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmallUmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
