/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.smalluml.SmallUml.ui.internal.SmallUmlActivator;

public class SmallUmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmallUmlActivator.getInstance().getInjector("org.smalluml.SmallUml");
	}

}
